// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBtransitions.ClassLibraryDatabase.DBContext;

#nullable disable

namespace ClassLibraryDatabase.Migrations
{
    [DbContext(typeof(NorthwindContext))]
    [Migration("20251130100254_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CustomerCustomerDemo", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerID");

                    b.Property<string>("CustomerTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerTypeID");

                    b.HasKey("CustomerId", "CustomerTypeId");

                    b.HasIndex("CustomerTypeId");

                    b.ToTable("CustomerCustomerDemo", (string)null);
                });

            modelBuilder.Entity("EmployeeTerritory", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("TerritoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("TerritoryID");

                    b.HasKey("EmployeeId", "TerritoryId");

                    b.HasIndex("TerritoryId");

                    b.ToTable("EmployeeTerritories", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.AlphabeticalListOfProduct", b =>
                {
                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discontinued")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("0");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuantityPerUnit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<short?>("ReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SupplierID");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("NUMERIC");

                    b.Property<short?>("UnitsInStock")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("UnitsOnOrder")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToView("Alphabetical list of products", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.AppState", b =>
                {
                    b.Property<string>("AppName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("AppName");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.Property<string>("ComponentName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ComponentName");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("DateCreated")
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("FilterFieldMaxValue")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("FilterFieldMaxValue");

                    b.Property<string>("FilterFieldName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("FilterFieldName");

                    b.Property<string>("FilterFieldValue")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("FilterFieldValue");

                    b.Property<byte>("FilterIsDateValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FilterIsDateValue");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("PagerBaseUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("PagerBaseUrl");

                    b.Property<int?>("PagerButtonCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PagerButtonCount");

                    b.Property<int?>("PagerPageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PagerPageCount");

                    b.Property<int?>("PagerPageNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PagerPageNumber");

                    b.Property<int?>("PagerPageSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PagerPageSize");

                    b.Property<int?>("PagerRowCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PagerRowCount");

                    b.Property<string>("SortState")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("SortState");

                    b.HasKey("AppName", "UserId", "ComponentName")
                        .HasName("PK_AppState");

                    b.ToTable("AppStates", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<byte[]>("Picture")
                        .HasColumnType("BLOB");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("CategoryId")
                        .HasName("PK_Categories");

                    b.HasIndex("CategoryName")
                        .HasDatabaseName("IX_CategoryName");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.CategorySalesFor1997", b =>
                {
                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CategorySales")
                        .HasColumnType("REAL");

                    b.ToTable((string)null);

                    b.ToView("Category Sales for 1997", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.CurrentProductList", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView("Current Product List", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Phone")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("CustomerId")
                        .HasName("PK_Customers");

                    b.HasIndex("City")
                        .HasDatabaseName("City");

                    b.HasIndex("CompanyName")
                        .HasDatabaseName("IX_Cust_CompanyName");

                    b.HasIndex("PostalCode")
                        .HasDatabaseName("IX_Cust_PostalCode");

                    b.HasIndex("Region")
                        .HasDatabaseName("Region");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.CustomerAndSuppliersByCity", b =>
                {
                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView("Customer and Suppliers by City", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.CustomerDemographic", b =>
                {
                    b.Property<string>("CustomerTypeId")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerTypeID");

                    b.Property<string>("CustomerDesc")
                        .HasColumnType("TEXT");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("CustomerTypeId")
                        .HasName("PK_CustomerDemographics");

                    b.ToTable("CustomerDemographics");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("DATE");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("DATE");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReportsTo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleOfCourtesy")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("EmployeeId")
                        .HasName("PK_Employees");

                    b.HasIndex("ReportsTo");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Invoice", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerID");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double>("Discount")
                        .HasColumnType("REAL");

                    b.Property<double?>("ExtendedPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("Freight")
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderID");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Salesperson")
                        .HasMaxLength(31)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipAddress")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipCity")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipCountry")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipPostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipRegion")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("ShipperName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("NUMERIC");

                    b.ToTable((string)null);

                    b.ToView("Invoices", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderID");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerID");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID");

                    b.Property<int?>("Freight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMERIC")
                        .HasDefaultValue(0);

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("ShipAddress")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipCity")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipCountry")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipPostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipRegion")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShipVia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("OrderId")
                        .HasName("PK_Orders");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("CustomersOrders");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("EmployeesOrders");

                    b.HasIndex("OrderDate")
                        .HasDatabaseName("OrderDate");

                    b.HasIndex("ShipPostalCode")
                        .HasDatabaseName("ShipPostalCode");

                    b.HasIndex("ShipVia")
                        .HasDatabaseName("ShippersOrders");

                    b.HasIndex("ShippedDate")
                        .HasDatabaseName("ShippedDate");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderID");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<double>("Discount")
                        .HasColumnType("REAL");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<short>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((short)1);

                    b.Property<double>("UnitPrice")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("OrderId", "ProductId")
                        .HasName("PK_Order_Details");

                    b.HasIndex("ProductId");

                    b.ToTable("Order Details", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.OrderDetailsExtended", b =>
                {
                    b.Property<double?>("Discount")
                        .HasColumnType("NUMERIC");

                    b.Property<double?>("ExtendedPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderID");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("NUMERIC");

                    b.ToTable((string)null);

                    b.ToView("Order Details Extended", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.OrderSubtotal", b =>
                {
                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderID");

                    b.Property<double?>("Subtotal")
                        .HasColumnType("REAL");

                    b.ToTable((string)null);

                    b.ToView("Order Subtotals", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.OrdersQry", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerID");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID");

                    b.Property<int?>("Freight")
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderID");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("ShipAddress")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipCity")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipCountry")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipPostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipRegion")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShipVia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("DATETIME");

                    b.ToTable((string)null);

                    b.ToView("Orders Qry", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Discontinued")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("0");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuantityPerUnit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<short?>("ReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SupplierID");

                    b.Property<double?>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<short?>("UnitsInStock")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("UnitsOnOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ProductId")
                        .HasName("PK_Products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("CategoriesProducts");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("IX_ProductName");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("SuppliersProducts");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.ProductDetailsV", b =>
                {
                    b.Property<string>("CategoryDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discontinued")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuantityPerUnit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<short?>("ReorderLevel")
                        .HasColumnType("NUMERIC");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SupplierID");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierRegion")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("NUMERIC");

                    b.Property<short?>("UnitsInStock")
                        .HasColumnType("NUMERIC");

                    b.Property<short?>("UnitsOnOrder")
                        .HasColumnType("NUMERIC");

                    b.ToTable((string)null);

                    b.ToView("ProductDetails_V", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.ProductSalesFor1997", b =>
                {
                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProductSales")
                        .HasColumnType("REAL");

                    b.ToTable((string)null);

                    b.ToView("Product Sales for 1997", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.ProductsAboveAveragePrice", b =>
                {
                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("REAL");

                    b.ToTable((string)null);

                    b.ToView("Products Above Average Price", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.ProductsByCategory", b =>
                {
                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discontinued")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("0");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuantityPerUnit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<short?>("UnitsInStock")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToView("Products by Category", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.QuarterlyOrder", b =>
                {
                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerID");

                    b.ToTable((string)null);

                    b.ToView("Quarterly Orders", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RegionID");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("RegionDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("RegionId")
                        .HasName("PK_Region");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.SalesByCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProductSales")
                        .HasColumnType("REAL");

                    b.ToTable((string)null);

                    b.ToView("Sales by Category", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.SalesTotalsByAmount", b =>
                {
                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderID");

                    b.Property<decimal?>("SaleAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("DATETIME");

                    b.ToTable((string)null);

                    b.ToView("Sales Totals by Amount", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Shipper", b =>
                {
                    b.Property<int>("ShipperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ShipperID");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Phone")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ShipperId")
                        .HasName("PK_Shippers");

                    b.ToTable("Shippers", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.SummaryOfSalesByQuarter", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderID");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("REAL");

                    b.ToTable((string)null);

                    b.ToView("Summary of Sales by Quarter", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.SummaryOfSalesByYear", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderID");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("REAL");

                    b.ToTable((string)null);

                    b.ToView("Summary of Sales by Year", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("SupplierID");

                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePage")
                        .HasColumnType("TEXT");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Phone")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("SupplierId")
                        .HasName("PK_Suppliers");

                    b.HasIndex("CompanyName")
                        .HasDatabaseName("IX_Sup_CompanyName");

                    b.HasIndex("PostalCode")
                        .HasDatabaseName("IX_Sup_PostalCode");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Territory", b =>
                {
                    b.Property<string>("TerritoryId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("TerritoryID");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("RegionDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RegionID");

                    b.Property<string>("TerritoryDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("TerritoryId")
                        .HasName("PK_Territories");

                    b.HasIndex("RegionId");

                    b.ToTable("Territories", (string)null);
                });

            modelBuilder.Entity("CustomerCustomerDemo", b =>
                {
                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .IsRequired();

                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.CustomerDemographic", null)
                        .WithMany()
                        .HasForeignKey("CustomerTypeId")
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeTerritory", b =>
                {
                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .IsRequired();

                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Territory", null)
                        .WithMany()
                        .HasForeignKey("TerritoryId")
                        .IsRequired();
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Employee", b =>
                {
                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Employee", "ReportsToNavigation")
                        .WithMany("InverseReportsToNavigation")
                        .HasForeignKey("ReportsTo");

                    b.Navigation("ReportsToNavigation");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Order", b =>
                {
                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Orders_Customers");

                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Orders_Employees");

                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Shipper", "ShipViaNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("ShipVia")
                        .HasConstraintName("FK_Orders_Shippers");

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("ShipViaNavigation");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.OrderDetail", b =>
                {
                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Details_Orders");

                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Details_Products");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Product", b =>
                {
                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Territory", b =>
                {
                    b.HasOne("WEBtransitions.ClassLibraryDatabase.DBContext.Region", "Region")
                        .WithMany("Territories")
                        .HasForeignKey("RegionId")
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Employee", b =>
                {
                    b.Navigation("InverseReportsToNavigation");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Region", b =>
                {
                    b.Navigation("Territories");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Shipper", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WEBtransitions.ClassLibraryDatabase.DBContext.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
